#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "precompiled/pchnkernel.h"
#include "precompiled/pchnnebula.h"
#include "resource/nresource.h"
#include "mathlib/triangle.h"
#include "conjurer/nobjecteditorstate.h"
#include "gfx2/ngfxutils.h"
#include "tools/nmeshbuilder.h"
#include "conjurer/ninguitool.h"
#include "conjurer/terrainundocmd.h"
#include "conjurer/inguiobjecttransform.h"
#include "conjurer/ninguiterraintoolgeom.h"
#include "conjurer/ninguitoolselection.h"
#include "nlevel/nlevel.h"
#include "util/nstringlist.h"
#include "nundo/nundoserver.h"
#include "nphysics/ncphysicsobj.h"
#include "conjurer/ninguitool.h"
#include "gui/nguiserver.h"
#include "gui/nguiwindow.h"
#include "gui/nguilabel.h"
#include "conjurer/neditorgrid.h"
#include "nnavmesh/nnavmesh.h"
#include "nphysics/nphysicsserver.h"
#include "mathlib/vector.h"
#include "mathlib/plane.h"
#include "gfx2/ngfxserver2.h"
#include "napplication/nappviewport.h"
