#include "ntestcmdprotocpp.h"

NCMDPROTOCPP_INITCMDS_BEGIN(nTestCmdProtoCPP)

    NCMDPROTOCPP_ADDCMD(Test0VV);

    NCMDPROTOCPP_ADDCMD(Test0IV);
    NCMDPROTOCPP_ADDCMD(Test0BV);
    NCMDPROTOCPP_ADDCMD(Test0FV);
    NCMDPROTOCPP_ADDCMD(Test0SV);
    NCMDPROTOCPP_ADDCMD(Test0OV);
    NCMDPROTOCPP_ADDCMD(Test0OV1);

    NCMDPROTOCPP_ADDCMD(Test0CIV);
    NCMDPROTOCPP_ADDCMD(Test0CBV);
    NCMDPROTOCPP_ADDCMD(Test0CFV);
    NCMDPROTOCPP_ADDCMD(Test0CSV);
    NCMDPROTOCPP_ADDCMD(Test0COV);
    NCMDPROTOCPP_ADDCMD(Test0COV1);

    NCMDPROTOCPP_ADDCMD(Test1VI);
    NCMDPROTOCPP_ADDCMD(Test1VB);
    NCMDPROTOCPP_ADDCMD(Test1VF);
    NCMDPROTOCPP_ADDCMD(Test1VS);
    NCMDPROTOCPP_ADDCMD(Test1VO);
    NCMDPROTOCPP_ADDCMD(Test1VO2);

    NCMDPROTOCPP_ADDCMD(Test1VCI);
    NCMDPROTOCPP_ADDCMD(Test1VCB);
    NCMDPROTOCPP_ADDCMD(Test1VCF);
    NCMDPROTOCPP_ADDCMD(Test1VCS);
    NCMDPROTOCPP_ADDCMD(Test1VCO);
    NCMDPROTOCPP_ADDCMD(Test1VCO2);

    NCMDPROTOCPP_ADDCMD(Test1II);
    NCMDPROTOCPP_ADDCMD(Test1BB);
    NCMDPROTOCPP_ADDCMD(Test1FF);
    NCMDPROTOCPP_ADDCMD(Test1SS);
    NCMDPROTOCPP_ADDCMD(Test1OO);
    NCMDPROTOCPP_ADDCMD(Test1OO2);

    NCMDPROTOCPP_ADDCMD(Test1CII);
    NCMDPROTOCPP_ADDCMD(Test1CBB);
    NCMDPROTOCPP_ADDCMD(Test1CFF);
    NCMDPROTOCPP_ADDCMD(Test1CSS);
    NCMDPROTOCPP_ADDCMD(Test1COO);
    NCMDPROTOCPP_ADDCMD(Test1COO2);

    NCMDPROTOCPP_ADDCMD(Test1ICI);
    NCMDPROTOCPP_ADDCMD(Test1BCB);
    NCMDPROTOCPP_ADDCMD(Test1FCF);
    NCMDPROTOCPP_ADDCMD(Test1SCS);
    NCMDPROTOCPP_ADDCMD(Test1OCO);
    NCMDPROTOCPP_ADDCMD(Test1OCO2);

    NCMDPROTOCPP_ADDCMD(Test1CICI);
    NCMDPROTOCPP_ADDCMD(Test1CBCB);
    NCMDPROTOCPP_ADDCMD(Test1CFCF);
    NCMDPROTOCPP_ADDCMD(Test1CSCS);
    NCMDPROTOCPP_ADDCMD(Test1COCO);
    NCMDPROTOCPP_ADDCMD(Test1COCO2);

    NCMDPROTOCPP_ADDCMD(Test6IIBFSOO);    
    NCMDPROTOCPP_ADDCMD(Test6ICICBCFCSCOCO);    
    NCMDPROTOCPP_ADDCMD(Test6VIBFSOO);    
    NCMDPROTOCPP_ADDCMD(Test6VCICBCFCSCOCO);    

    NCMDPROTOCPP_ADDCMD(Test0V3V);
    NCMDPROTOCPP_ADDCMD(Test0CV3V);
    NCMDPROTOCPP_ADDCMD(Test0V3PV);
    NCMDPROTOCPP_ADDCMD(Test0CV3PV);

    NCMDPROTOCPP_ADDCMD(Test1VV3);
    NCMDPROTOCPP_ADDCMD(Test1VCV3);
    NCMDPROTOCPP_ADDCMD(Test1VV3P);
    NCMDPROTOCPP_ADDCMD(Test1VCV3P);

    NCMDPROTOCPP_ADDCMD(OutTest1V3);
    NCMDPROTOCPP_ADDCMD(OutTest1IV3);    

    NCMDPROTOCPP_ADDCMD(RefTest1VI);
    NCMDPROTOCPP_ADDCMD(RefTest1VB);
    NCMDPROTOCPP_ADDCMD(RefTest1VF);
    NCMDPROTOCPP_ADDCMD(RefTest1VS);
    NCMDPROTOCPP_ADDCMD(RefTest1VO);
    NCMDPROTOCPP_ADDCMD(RefTest1VO2);

    NCMDPROTOCPP_ADDCMD(RefTest1II);
    NCMDPROTOCPP_ADDCMD(RefTest1BB);
    NCMDPROTOCPP_ADDCMD(RefTest1FF);
    NCMDPROTOCPP_ADDCMD(RefTest1SS);
    NCMDPROTOCPP_ADDCMD(RefTest1OO);
    NCMDPROTOCPP_ADDCMD(RefTest1OO2);

    NCMDPROTOCPP_ADDCMD(InOutTest1IV3);

NCMDPROTOCPP_INITCMDS_END()

