#ifndef __PCH_NNEBULA__
#define __PCH_NNEBULA__

#include "precompiled/pchnkernel.h"

#include "gfx2/ngfxserver2.h"
#include "gfx2/nshader2.h"
#include "script/nbinscriptserver.h"
#include "script/ntclserver.h"
#include "file/nnpkfileserver.h"
#include "file/nnpkfilewrapper.h"
#include "file/nnpkfile.h"
#include "file/nnpkdirectory.h"
#include "variable/nvariableserver.h"
#include "input/ninputserver.h"
#include "input/ninputdevice.h"
#include "input/njoystickdevice.h"
#include "input/nrelmousedevice.h"
#include "input/nkeyboarddevice.h"
#include "input/ninputlogevent.h"
#include "resource/nresourceserver.h"
#include "gfx2/nn3d2loader.h"
#include "gfx2/nnvx2loader.h"
#include "gfx2/nmesharray.h"
#include "gfx2/nsurface.h"
#include "audio3/naudioserver3.h"
#include "audio3/nsound3.h"
#include "audio3/nsoundresource.h"
#include "anim2/nmemoryanimation.h"
#include "misc/nconserver.h"
#include "particle/nparticle.h"
#include "particle/nparticleemitter.h"
#include "gfx2/nwindowhandler.h"
#include "gfx2/nwin32windowhandler.h"
#include "misc/nprefserver.h"
#include "misc/nwin32prefserver.h"
#include "misc/nobjectarray.h"
#include "xml/nxmlspreadsheet.h"
#include "locale/nlocaleserver.h"
#include "shadow2/nshadowcaster2.h"
#include "shadow2/nstaticshadowcaster2.h"
#include "shadow2/nskinnedshadowcaster2.h"
#include "video/nvideoserver.h"

#endif
